// app/layout.tsx
import { ClerkProvider } from "@clerk/nextjs";
import { Suspense } from "react";
import { fontVariables } from "@/lib/fonts";
import { cn } from "@/lib/utils";
import type { Metadata } from "next";
import { ThemeProvider } from "next-themes";
import NextTopLoader from "nextjs-toploader";
import { Toaster } from "sonner";
import { QueryProvider } from "@/components/providers/query-provider";
import "./globals.css";
import { ThemeDataProvider } from "@/components/providers/theme-data-provider";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" suppressHydrationWarning>
			<body
				suppressHydrationWarning
				className={cn("bg-background group/layout font-sans", fontVariables)}
			>
				<ThemeProvider
					attribute="class"
					defaultTheme="light"
					enableSystem
					disableTransitionOnChange
				>
					<QueryProvider>
						<NextTopLoader
							color="var(--primary)"
							showSpinner={false}
							height={2}
						/>
						<Toaster position="top-center" richColors />

						{/* ClerkProvider with dynamic inside Suspense for PPR */}
						<Suspense fallback={<AppSkeleton />}>
							<ClerkProvider dynamic>
								<Suspense fallback={children}>
									<ThemeDataProvider>{children}</ThemeDataProvider>
								</Suspense>
							</ClerkProvider>
						</Suspense>
					</QueryProvider>
				</ThemeProvider>
			</body>
		</html>
	);
}

function AppSkeleton() {
	return <div className="min-h-screen" />;
}
