import { ActiveThemeProvider } from "@/components/active-theme";
import { fontVariables } from "@/lib/fonts";
import GoogleAnalyticsInit from "@/lib/ga";
import { DEFAULT_THEME, ThemeType } from "@/lib/themes";
import { cn } from "@/lib/utils";
import { ClerkProvider } from "@clerk/nextjs";
import type { Metadata } from "next";
import { ThemeProvider } from "next-themes";
import { cookies } from "next/headers";
import NextTopLoader from "nextjs-toploader";
import { Toaster } from "sonner";
import "./globals.css";
export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const cookieStore = await cookies();

	const contentLayoutValue =
		cookieStore.get("theme_content_layout")?.value ??
		DEFAULT_THEME.contentLayout;
	const contentLayout: ThemeType["contentLayout"] =
		contentLayoutValue === "centered" ? "centered" : "full";

	const isSidebarValue = cookieStore.get("theme_issidebar")?.value;
	const isSidebar =
		isSidebarValue === "false" ? false : DEFAULT_THEME.isSidebar;

	const themeSettings: ThemeType = {
		preset: cookieStore.get("theme_preset")?.value ?? DEFAULT_THEME.preset,
		scale: cookieStore.get("theme_scale")?.value ?? DEFAULT_THEME.scale,
		radius: cookieStore.get("theme_radius")?.value ?? DEFAULT_THEME.radius,
		contentLayout,
		isSidebar,
	};

	const bodyAttributes = Object.fromEntries(
		Object.entries(themeSettings)
			.filter(([_, value]) => value)
			.map(([key, value]) => [
				`data-theme-${key.replace(/([A-Z])/g, "-$1").toLowerCase()}`,
				value,
			])
	);

	return (
		<ClerkProvider>
			<html lang="en" suppressHydrationWarning>
				<body
					suppressHydrationWarning
					className={cn("bg-background group/layout font-sans", fontVariables)}
					{...bodyAttributes}
				>
					<ThemeProvider
						attribute="class"
						defaultTheme="light"
						enableSystem
						disableTransitionOnChange
					>
						<ActiveThemeProvider initialTheme={themeSettings}>
							{children}
							<Toaster position="top-center" richColors />
							<NextTopLoader
								color="var(--primary)"
								showSpinner={false}
								height={2}
								shadow-sm="none"
							/>
							{process.env.NODE_ENV === "production" ? (
								<GoogleAnalyticsInit />
							) : null}
						</ActiveThemeProvider>
					</ThemeProvider>
				</body>
			</html>
		</ClerkProvider>
	);
}
